import Link from 'next/link';
import {
  Globe,
  ClipboardList,
  Briefcase,
  AlertTriangle,
  FileText,
  RefreshCw,
  Inbox,
  type LucideIcon,
} from 'lucide-react';

import { PageHeader } from '@/components/ui/PageHeader';
import { Card } from '@/components/ui/Card';

interface LifecycleStep {
  icon: LucideIcon;
  title: string;
  href: string;
  what: string;
  who: string;
}

// ponytail: static explainer page — no data fetching, content is the product.
const STEPS: LifecycleStep[] = [
  {
    icon: Globe,
    title: '1. Audit Universe',
    href: '/audit/universe',
    what: 'The registry of everything that can be audited — departments, systems, processes — each with a risk score fed by the Risk Register.',
    who: 'Maintained by audit admins; read by everyone planning audits.',
  },
  {
    icon: ClipboardList,
    title: '2. Audit Plans',
    href: '/audit/plans',
    what: 'The annual plan picks which universe entities get audited this year, prioritised by risk. A submitted plan goes through workflow approval before engagements can start.',
    who: 'Drafted by audit leads/admins; approved via the approval chain.',
  },
  {
    icon: Briefcase,
    title: '3. Engagements (fieldwork)',
    href: '/audit/engagements',
    what: 'One engagement = one audit. Inside it you run control checklists, write working papers, and attach evidence. Status advances automatically as gates are met — the only manual steps are "Start fieldwork" and "Issue report". The What’s-next panel on each engagement tells you exactly what is blocking progress and who it is waiting on.',
    who: 'Lead auditor and assigned staff do the work; the audit manager reviews.',
  },
  {
    icon: AlertTriangle,
    title: '4. Findings',
    href: '/audit/findings',
    what: 'Issues raised during fieldwork — often straight from a failed checklist control. Each finding is assigned to an auditee, who responds with a remediation plan and evidence.',
    who: 'Raised by auditors; responded to by the auditee; verified by the auditor; closure is formally approved.',
  },
  {
    icon: FileText,
    title: '5. Reports',
    href: '/audit/reports',
    what: 'The engagement’s report summarises scope, methodology, and findings. It is submitted through a multi-level Approve & Sign chain (manager → director → CAE) and then issued to the auditee.',
    who: 'Generated by the lead auditor; signed by each approval level.',
  },
  {
    icon: RefreshCw,
    title: '6. Follow-up & closure',
    href: '/audit/findings',
    what: 'After the report is issued, each finding gets a follow-up: the auditee uploads remediation evidence, the auditor verifies it, and once every finding is closed the engagement closes.',
    who: 'Auditee remediates; auditor verifies; manager approves closure.',
  },
];

export default function HelpPage(): JSX.Element {
  return (
    <div>
      <PageHeader
        title="How IAMS works"
        subtitle="The internal audit lifecycle, from planning to closure — and where each step lives."
      />

      <Card padded className="mb-4">
        <p className="text-sm text-text-secondary">
          IAMS follows one continuous flow. Nothing moves to the next stage by hand — the system
          advances an engagement automatically once the current stage&apos;s requirements are met, so
          if something looks stuck, open it and check the <span className="font-medium text-text-primary">What&apos;s next</span> panel:
          it names the exact requirement (or person) the work is waiting on.
        </p>
      </Card>

      <ol className="space-y-3">
        {STEPS.map((s) => {
          const Icon = s.icon;
          return (
            <li key={s.title}>
              <Card padded>
                <div className="flex items-start gap-3">
                  <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
                    <Icon className="h-4.5 w-4.5" />
                  </span>
                  <div className="min-w-0">
                    <Link href={s.href} className="text-sm font-semibold text-primary hover:underline">
                      {s.title}
                    </Link>
                    <p className="mt-1 text-sm text-text-secondary">{s.what}</p>
                    <p className="mt-1 text-xs text-text-muted">
                      <span className="font-semibold uppercase tracking-wider">Who:</span> {s.who}
                    </p>
                  </div>
                </div>
              </Card>
            </li>
          );
        })}
      </ol>

      <Card padded className="mt-4">
        <div className="flex items-start gap-3">
          <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
            <Inbox className="h-4.5 w-4.5" />
          </span>
          <div>
            <p className="text-sm font-semibold text-text-primary">Approvals run alongside everything</p>
            <p className="mt-1 text-sm text-text-secondary">
              Plans, working papers, reports, and finding closures all pass through the{' '}
              <Link href="/workflow/approvals" className="text-primary hover:underline">
                approvals inbox
              </Link>
              . When something reaches your level you get a notification; open the item, review it via
              the &ldquo;Review before signing&rdquo; link, then Approve &amp; Sign or Reject with a reason.
            </p>
          </div>
        </div>
      </Card>
    </div>
  );
}
